import Link from 'next/link';
import { ChevronLeft, ChevronRight, Play, Radio } from 'lucide-react';
import { AnimatedPage } from '@/components/AnimatedPage';
import { ServerStatusBar } from '@/components/ServerStatus';
import { SubscriptionCards } from '@/components/SubscriptionCards';
import { getServerStatuses } from '@/lib/fivem';
import { jobCards, siteConfig, streamers } from '@/lib/data';
import { getSettings } from '@/lib/settings';

export default async function HomePage() {
  const settings = getSettings();
  const servers = await getServerStatuses(settings.server.maxPlayers);
  return (
    <AnimatedPage>
      <section className="relative min-h-screen overflow-hidden bg-[var(--bg-primary)] px-5 pb-24 pt-8">
        <div className="relative mx-auto grid max-w-7xl items-center gap-10 pt-6 lg:grid-cols-[1.1fr_.9fr]">
          <div><p className="font-mono text-sm uppercase tracking-[0.35em] text-[var(--red-primary)]">Mythic Framework Roleplay</p><h1 className="pulse-heading mt-5 text-6xl text-white md:text-8xl xl:text-9xl">Join into a world of <span className="text-[var(--red-primary)]">limitless possibilities</span></h1><p className="mt-6 max-w-xl text-lg text-[var(--text-secondary)]">Unleash your imagination, create unforgettable stories, and connect with fellow roleplayers on our vibrant community website.</p><div className="mt-8 flex flex-wrap gap-4"><Link href="/applications" className="pulse-button bg-[var(--red-primary)] px-6 py-4 text-white">Apply Now</Link><a href={siteConfig.discordUrl} className="pulse-button border border-[var(--red-primary)] px-6 py-4 text-[var(--red-primary)] hover:bg-[var(--red-primary)] hover:text-white">Join Discord</a></div></div>
          <div className="hidden justify-center lg:flex"><div className="grid h-[30rem] w-[30rem] place-items-center overflow-hidden rounded-full bg-[rgba(255,26,26,0.05)] shadow-[0_0_80px_rgba(255,26,26,.15)]">{settings.branding.logoUrl ? <img src={settings.branding.logoUrl} alt={`${settings.branding.siteName} server logo`} className="h-[28rem] w-[28rem] object-contain" /> : <Radio size={220} className="text-[var(--red-primary)] opacity-70" />}</div></div>
        </div>
        <div className="relative mx-auto mt-16 max-w-7xl"><ServerStatusBar servers={servers} maxPlayers={settings.server.maxPlayers} /></div>
      </section>
      <section className="bg-[var(--bg-secondary)] px-5 py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><h2 className="pulse-heading text-6xl text-[var(--red-primary)]">About Us</h2><p className="mt-5 text-[var(--text-secondary)]">Pulse RP is a premium FiveM GTA V roleplay community engineered for cinematic stories, competitive energy, and serious character development. Built around the Mythic Framework, our city rewards creativity, discipline, and high-stakes immersion.</p><div className="mt-8 flex gap-4"><a href={siteConfig.discordUrl} className="pulse-button border border-[var(--red-primary)] px-5 py-3 text-[var(--red-primary)]">Join our Discord</a><Link href={siteConfig.rulesUrl} className="pulse-button border border-white/25 px-5 py-3 text-white">Read the Rules</Link></div></div><div className="grid grid-cols-2 gap-4">{[1,2,3,4].map((i)=><div key={i} className="angled h-44 border border-[var(--border)] bg-[linear-gradient(135deg,#242424,#080808)] hover:border-[var(--red-primary)]" />)}</div></div></section>
      <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><h2 className="pulse-heading text-center text-6xl">Our Streamers</h2><p className="mx-auto mt-4 max-w-2xl text-center text-[var(--text-secondary)]">See Pulse RP come alive with our official live streamer hub. Updated in real time with live badges, platforms, and viewer counts.</p><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{streamers.map((s)=><a key={s.name} href="#" className="group pulse-panel relative h-64 overflow-hidden rounded-xl hover:border-[var(--red-primary)]"><div className="absolute inset-0 bg-[linear-gradient(135deg,#333,#080808)] transition group-hover:scale-105" /><div className="absolute left-4 top-4 flex items-center gap-2 rounded bg-black/60 px-3 py-1 font-mono text-xs"><Play size={14}/>{s.platform}</div>{s.live && <div className="absolute right-4 top-4 rounded-full bg-[var(--red-primary)] px-3 py-1 font-mono text-xs font-bold">LIVE</div>}<div className="absolute inset-0 grid place-items-center"><div className="grid h-14 w-14 place-items-center rounded-full bg-white text-black"><Play fill="black" /></div></div><div className="absolute bottom-4 left-4"><div className="font-mono text-sm">👁 {s.viewers}</div><div className="pulse-heading text-3xl">{s.name}</div></div></a>)}</div></div></section>
      {settings.subscriptions.enabled && <section className="bg-[var(--bg-secondary)] px-5 py-24"><div className="mx-auto max-w-7xl"><h2 className="pulse-heading text-center text-6xl">Subscriptions</h2><p className="mb-12 mt-4 text-center text-[var(--text-secondary)]">Choose your membership and get many benefits to use in the city.</p><SubscriptionCards subscriptions={settings.subscriptions} /></div></section>}
      <section className="bg-[#080808] px-5 py-24"><div className="mx-auto max-w-7xl"><h2 className="pulse-heading text-center text-6xl text-[var(--red-primary)]">Job Applications</h2><p className="mx-auto mt-5 max-w-5xl text-center text-sm leading-6 text-white/80">Pulse RP is a roleplay community built on quality, performance, and immersive character stories. Our departments help shape the city every day through emergency response, justice, investigation, and civilian interaction.</p><div className="relative mx-auto mt-10 max-w-4xl"><button aria-label="Previous applications" className="absolute -left-12 top-1/2 hidden h-9 w-9 -translate-y-1/2 place-items-center rounded-full border border-white/10 bg-black/40 text-white/45 transition hover:border-[var(--red-primary)] hover:text-white lg:grid"><ChevronLeft size={16} /></button><div className="grid gap-7 md:grid-cols-3">{jobCards.map(({title, href}, index)=><Link key={title} href={href} className="group relative h-[405px] overflow-hidden bg-[#111] shadow-[0_18px_40px_rgba(0,0,0,0.45)]"><div className={`absolute inset-0 transition duration-500 group-hover:scale-105 ${index === 0 ? 'bg-[linear-gradient(180deg,rgba(0,0,0,.12),rgba(0,0,0,.78)),radial-gradient(circle_at_45%_20%,rgba(255,255,255,.20),transparent_18%),linear-gradient(135deg,#1b2430,#050505)]' : index === 1 ? 'bg-[linear-gradient(180deg,rgba(0,0,0,.10),rgba(0,0,0,.75)),linear-gradient(135deg,#26323a,#071014_45%,#1a1010)]' : 'bg-[linear-gradient(180deg,rgba(0,0,0,.15),rgba(0,0,0,.76)),linear-gradient(135deg,#2b2118,#080606_55%,#15100a)]'}`} /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(0,0,0,.2),transparent_45%,rgba(0,0,0,.35))]" /><div className="absolute bottom-10 left-0 right-0 text-center"><h3 className="pulse-heading text-4xl text-white drop-shadow-[0_2px_8px_rgba(0,0,0,.8)]">{title.toUpperCase()}</h3><div className="mx-auto mt-2 h-[2px] w-20 bg-white/50 transition group-hover:bg-[var(--red-primary)]" /></div></Link>)}</div><button aria-label="Next applications" className="absolute -right-12 top-1/2 hidden h-9 w-9 -translate-y-1/2 place-items-center rounded-full border border-white/10 bg-black/40 text-white/45 transition hover:border-[var(--red-primary)] hover:text-white lg:grid"><ChevronRight size={16} /></button></div></div></section>
    </AnimatedPage>
  );
}
